ifconfig
python3 main.py
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install python-imaging
sudo apt-get install python-imaging-tk
python3 main.py
sudo apt-get install python3-pil
sudo apt-get install python3-imaging-tk
sudo reboot
python3 main.py
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
python3 main.py
sudo apt-get install python-imaging-tk
python3 main.py
sudo reboot
python3 main.py
sudo nano /boot/config.txt
sudo reboot
python3 main.py
pip3 install pillow
pip3 install Pillow
python3 main.py
pip3 install Pillow
python3 main.py
sudo apt-get installpython3-pil imagetk
sudo apt-get install python3-pil imagetk
python3 main.py
sudo apt-get install python3-
sudo apt-get install python3-Pil imagetk
sudo apt-get install python3-pil imagetk
python-V
python -V
python3 main.py
sudo apt-get install python-imaging-tk
sudo reboot
sudo 
sudo apt-get install libjpeg8-dev
python3 main.py
find /usr/lib -name libjpeg.so
sudo In -s /usr/lib/arm-linux-gnueabihf/libjpeg.so /usr/lib/
sudo ln -s /usr/lib/arm-linux-gnueabihf/libjpeg.so /usr/lib/
sudo In -s /usr/lib/arm-linux-gnueabihf/libjpeg.so /usr/lib/
192.168.0.52
sudo apt-get install python-pip
sudo pip install PIL
I
I and T
sudo apt-get install python-imaging-TK
sudo apt-get install python-imaging-Tk
python3 main.py
python3 password\ gen.py
apt-get install python3-pil python3-pil.imagetk
python3 main.py
sudo apt-get install python3-pil.imagetk
sudo apt-get install python-imaging-tksudo apt-get install python-imaging-tk
sudo apt-get install python-imaging-tk
python3 main.py
sudo pip install ummalqura
python3 main.py
sudo reboot
python3 main.py
sudo apt-get install python-imaging-tk
python3 main.py
pip install requests
python3 main.py
pip3 install pytest
python3 main.py
pip3 uninstall requests
pipenv shell
pytest --version
python3 main.py
pytest
python -m pytestpython
(env) pip install pytest
pip install pytest
pytest
python3 main.py
import 
import sys
__init__.py
python3 main.py
Install Python3 and Python3-pip
sudo apt-get install python3 python3-pipsudo apt-get install python3 python3-pip
python3 main.py
pip3 install pandas
python3 main.py
sudo apt-get install python3 python3-pip
python3 main.py
condo install pip
sudo apt install python.pip
python3 main.py
sudo python3 -m pip install ummalqura
python3 main.py
sudo reboot
sudo apt-get update
sudo apt-get upgrade
sudo raspi-config
sudo apt-get install ntfs-3g
sudo apt-get install samba samba-common-bin
sudo mkdir /external
ls /
sudo mkdir /External
ls /
cl
lsblk
sudo monut /dev/sda2 /external/
sudo nano /etc/samba/smb.conf
sudo mount /External
lsblk
sudo nano /etc/samba/smb.conf
sudo /etc/init.d/samba restart
lsblk
sudo nano /etc/samba/smb.conf
lsblk
sudo nano /etc/samba/smb.conf
sudo /etc/init.d/samba restart
ls /bin/
lsblk
sudo nano /etc/samba/smb.conf
sudo /etc/init.d/samba restart
lsblk
clear
sudo mount /External
sudo nano /etc/samba/smb.conf
sudo /etc/init.d/samba restart
sudo nano /etc/samba/smb.conf
sudo /etc/init.d/samba restart
sudo apt-get install samba samba-common-bin
sudo nano /etc/samba/smb.conf
sudo smbpasswd user -pi
sudo nano /etc/samba/smb.conf
sudo nano /boot/config.txt
sudo apt-get install ntfs-3g
sudo apt-get install samba samba-common-bin
sudo mkdir  /External
lsblk
sudo mkdir  /External /media/pi/Nawii
sudo mkdir  /External
sudo blkid
sudo mount /dev/sda2 /mnt/external
sudo mount /dev/sda2 /mnt/mydisk
sudo blkid
lsblk
sudo mkdir  /External
mkdir /mnt/
mkdir: cannot create directory ‘/mnt/sda2’: Permission denied
sudo mkdir  /External
cd /dev
ls
df
tail -f /var/log/messages
sudo fdisk -l
cd /monut
cd /mount
cd /mnt
cd /nawii
ls
lsdblk
lsblk
cd /mnt
cd /media
cd /mnt
mkdir usbstick
sudo mkdir usbstick
sudo mount -t vfat -o uid
sudo mount -t vfat -o uid=pi,gid=pi /dev/sda1 /mnt/usbstick
lsblk
sudo mkdir  /External
t $ sudo mount -t vfat -o uid
sudo mkdir /External/01
sudo mkdir /External/02
sudo mount /dev/sda1 /External/
sudo mount /dev/sdb1 /External/02
sudo /etc/samba/smb.conf
python3 main.py
sudo mount /dev/sdb1 /External/02
sudo mkdir /External/
sudo mkdir /External
lsblk
sudo blkid
sudo nano /etc/fstab
sudo mount /dev/sda1 /mnt
sudo blkid
sudo mkdir /mnt/volume
sudo chmod 770 /mnt/volume
sudo mount -t ntfs-3g -o nofail,uid=1000,gid=1000,umask=007 /dev/sda1 /mnt/volume
sudo mount /dev/sda1 /mnt/volume
lsblk
sudo mkdir /external
mkdir: cannot create directory ‘/external’: File exists
python3 main.py
sudo apt-get install exfat-utils exfat-fuse
lsblk
sudo mkdir  /External
sudo mkdir /External
ls -l
cd /mnt
cd /media
cd /mnt
mkdir usbstick
sudo mkdir
sudo mkdir usbstick
sudo mount /dev/ls
lsdlk
sudo blkld
sudo blkid
sudo nano /boot/config.txt
sudo reboot
ifconfig
